### ISSUE TITLE
php7 + ext-ssh2 on debian 8 ?

### ISSUE THREAD

**Issue by ibasaw** [Herzult/php-ssh#52]
hot to install the dependency extension ext-ssh2 on debian 8 ?

```
- herzult/php-ssh v1.1.1 requires ext-ssh2 * -> the requested PHP extension ssh2 is missing from your system
```

**Comment by h4cc** [comment]
If this will not bring something up

```
apt-cache search php | grep ssh
```

then something like this should do the trick:

```
sudo apt-get install libssh2-1 libssh2-1-dev
sudo pecl install ssh2 channel://pecl.php.net/ssh2-0.12
```

**Comment by ibasaw** [comment]
pecl install ssh2 channel://pecl.php.net/ssh2-0.12
Failed to download pecl/ssh2 within preferred state "stable", latest release is version 0.12, stability "beta", use "channel://pecl.php.net/ssh2-0.12" to install
pecl/ssh2 requires PHP (version >= 4.0.0, version <= 6.0.0), installed version is 7.0.2-1~dotdeb+8.1
No valid packages found
install failed

**Comment by CaredduMattia** [comment]
https://medium.com/php-7-tutorial/solution-how-to-compile-php7-with-ssh2-f23de4e9c319#.p5dngt2no

**Comment by ibasaw** [comment]
@CaredduMattia : don't work for me, error in compil

**Comment by easterism** [comment]
Currently the PHP7 supported by 1.0 (Alpha) only. So use 
`pecl install ssh2 channel://pecl.php.net/ssh2-1.0`
or download the source http://pecl.php.net/get/ssh2-1.0.tgz and use 
`pecl install ssh2 /home/you/ssh2-1.0.tgz`
